set viminfofile=$XDG_CONFIG_HOME/vim/info

set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on
set number
set cursorline

set shiftwidth=4
set tabstop=5
set expandtab
set incsearch
set ignorecase
set smartcase
set showmatch
set hlsearch
set wildmenu
